# number_of_retries: 10

# path to TPT, should be defined for the script main.py to run
main_script_path: ~/TPTDailyReportDownloader


report_paths: [
  "tests/test_data/reports/",
  "/path/to/reports1",
  "/path/to/reports2",
]

# Test if it would work with the test i have there
report_dir: "~/0x02_dev_env/report_sentinel/tests/test_data/reports"

# Email configs
# smtp_server: ["smtp.test.com", 465]  # One or the other
smtp_server: ["127.0.0.1", 1025]
smtp_username: "user@test.com"
smtp_password: "password"
sender: "noreply@algosciences.com"
recipients: ["person1@mail.com"]
